### ISSUE TITLE
List of known bugs

### ISSUE THREAD

**Issue by djagt** [CyberneticSCL/PIETOOLS#4] opened 2021-10-02 04:21 UTC
SOSTOOLS400/ dpvar/ @dpvar/ subs:
Issue in the case where substitution returns a constant. Previous implementation resulted in the dpvar coefficient matrix to be specified by a polynomial class object, resulting in errors. The check "isdouble" has been replaced by "isa(...,double)", resolving this issue.

**Comment by sachin-shivakumar** [comment] 2021-10-15 10:50
The fix seems to work as intended. Closing the issue. Thanks

**Closed by sachin-shivakumar** 2021-10-15 10:50 UTC
Labels: bug
